{% set version = "4.0.2" %}

package:
  name: nbdime
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/n/nbdime/nbdime-{{ version }}.tar.gz
  sha256: d8279f8f4b236c0b253b20d60c4831bb67843ed8dbd6e09f234eb011d36f1bf2

build:
  number: 1
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - git-nbdiffdriver = nbdime.vcs.git.diffdriver:main
    - git-nbdifftool = nbdime.vcs.git.difftool:main
    - git-nbmergedriver = nbdime.vcs.git.mergedriver:main
    - git-nbmergetool = nbdime.vcs.git.mergetool:main
    - hg-nbdiff = nbdime.vcs.hg.diff:main
    - hg-nbdiffweb = nbdime.vcs.hg.diffweb:main
    - hg-nbmerge = nbdime.vcs.hg.merge:main
    - hg-nbmergeweb = nbdime.vcs.hg.mergeweb:main
    - nbdiff = nbdime.nbdiffapp:main
    - nbdiff-web = nbdime.webapp.nbdiffweb:main
    - nbdime = nbdime.__main__:main_dispatch
    - nbmerge = nbdime.nbmergeapp:main
    - nbmerge-web = nbdime.webapp.nbmergeweb:main
    - nbshow = nbdime.nbshowapp:main
requirements:
  host:
    - hatch-jupyter-builder >=0.5
    - hatchling >=1.5.0
    - jupyterlab >=4.0.0,<5
    - pip
    - python {{ python_min }}
  run:
    - colorama
    - gitpython !=2.1.4,!=2.1.5,!=2.1.6
    - jinja2 >=2.9
    - jupyter_server
    - jupyter-server-mathjax >=0.2.2
    - nbformat
    - pygments
    - python >={{ python_min }}
    - requests
    - tornado

test:
  requires:
    - jupyterlab >=4.0.0,<5.0.0a0
    - m2-grep  # [win]
    - pip
    - python {{ python_min }}
  imports:
    - nbdime
  commands:
    - pip check
    - nbdime show -h
    - nbshow -h
    - nbdiff -h
    - nbdiff-web -h
    - nbmerge -h
    - nbmerge-web -h
    - git-nbdifftool -h
    - git-nbmergetool -h
    - git-nbdiffdriver -h
    - git-nbmergedriver -h
    - hg-nbdiff -h
    - hg-nbdiffweb -h
    - hg-nbmerge -h
    - hg-nbmergeweb -h
    # print them all for debugging
    - jupyter labextension list
    - jupyter server extension list
    # write out lists to grep
    - jupyter labextension list 1>labextensions 2>&1
    - jupyter server extension list 1>server_extensions 2>&1
    # check files
    - grep -iE "nbdime-jupyterlab.*OK*" labextensions
    - grep -iE "nbdime.*OK" server_extensions

about:
  home: https://nbdime.readthedocs.io
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE.md
    - nbdime/labextension/static/third-party-licenses.json
  summary: Diff and merge of Jupyter Notebooks
  doc_url: https://nbdime.readthedocs.io
  dev_url: https://github.com/jupyter/nbdime

extra:
  recipe-maintainers:
    - kain88-de
    - minrk
    - ocefpaf
    - bollwyvl
